FROM golang:1.16-alpine as dev
# ワーキングディレクトリの設定
ENV ROOT=/usr/src
WORKDIR ${ROOT}
# アップデートとgitのインストール
RUN apk update && apk add git bash gcc musl-dev make && apk add --no-cache coreutils
# ホストのファイルをコンテナの作業ディレクトリに移行
# 依存関係
COPY go.mod go.sum ./
RUN go mod download

WORKDIR ${ROOT}/app

# ソースコードとか変更頻度が高いものは後
COPY . .
EXPOSE 8080

CMD ["go", "run", "./cmd/pokewordle_solver/main.go"]