version: "3" # 3が最新
services:
  app:
    container_name: go-container
    build:  # ビルドに使うDockerfileの場所
      context: .
      dockerfile: Dockerfile.dev
    tty: true # コンテナの永続化
    ports:
      - "8080:8080"