name: app-test

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        run: |
          make all-gha